import type { Metadata } from "next";
import type { CSSProperties, ReactNode } from "react";
import "./globals.scss";

const fontVariables = {
  "--font-geist-sans":
    '"Inter", "Segoe UI", Arial, Helvetica, sans-serif',
  "--font-geist-mono":
    '"SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace',
} as CSSProperties;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" style={fontVariables}>
      <body>{children}</body>
    </html>
  );
}
